### ISSUE TITLE
bug(python): Python table.search() and Rust table.nearest_to() return different result.

### ISSUE THREAD

**Issue by laonger** [lancedb/lancedb#1633]
### What happened?

hi, I searched same vector data by Python sdk and Rust, then I get two different result: 

Rust:
``` 

        let results = self.table.query()
            .nearest_to(query_vector)
            .unwrap()
            .limit(10)
            .execute()
            .await?
            .try_collect::<Vec<RecordBatch>>()
            .await?

```
get only one result and refered text is: "update_summary"

Python:
``` 

table.search(v)
```
get 10 results and the first refered text is: "whole project summary"

please tell me how to fix it, 

Thanks very much.

**Comment by laonger** [comment]
Python: 
```
In [69]: t.search(v).__dict__
Out[69]:
{'_table': LanceTable(connection=LanceDBConnection(.readit/db), name="vectors"),
 '_limit': 10,
 '_columns': None,
 '_where': None,
 '_with_row_id': False,
 '_query': array([ 0.00467143, -0.01212643, -0.00172388, ..., -0.02341503,
         0.00321902, -0.04500008], dtype=float32),
 '_metric': 'L2',
 '_nprobes': 20,
 '_refine_factor': None,
 '_vector_column': 'embedings',
 '_prefilter': False,
 '_reranker': None,
 '_str_query': None}
```

Rust:
```
query_vector: Some(PrimitiveArray<Float32>
[
  0.004671432,
  -0.012126431,
  -0.0017238824,
  0.006217552,
  -0.042155884,
  -0.0323004,
  0.0081798285,
  0.1031849,
  -0.017759709,
  0.026259234,
  ...1004 elements...,
  0.022731546,
  0.014684006,
  -0.016591161,
  0.020945653,
  0.029235722,
  -0.0038969938,
  -0.039995175,
  -0.023415035,
  0.0032190161,
  -0.045000084,
]), nprobes: 20, refine_factor: Some(1), distance_type: None, use_index: true, prefilter: true}
```

I find in Python, the query object's `_prefilter ` attibute is `False`, and in Rust is `true`(prefilter), is that the reason? 

how can I change it to `false` in Rust? 

thx

**Comment by wjones127** [comment]
To turn off prefilter in Rust, call the `postfilter` method: https://docs.rs/lancedb/latest/lancedb/query/struct.VectorQuery.html#method.postfilter

**Comment by laonger** [comment]
thx @wjones127 's reply.

but....

Set prefilter to `false` is no use. The problem still **exists**.


> To turn off prefilter in Rust, call the `postfilter` method: https://docs.rs/lancedb/latest/lancedb/query/struct.VectorQuery.html#method.postfilter

**Comment by wjones127** [comment]
I still think it's likely there are just different defaults between Rust and Python. I'd recommend calling `explain_plan()` on each and posting them here. Then we can find what differences there are in what they are executing.

https://lancedb.github.io/lancedb/python/python/#lancedb.query.LanceQueryBuilder.explain_plan
https://docs.rs/lancedb/latest/lancedb/query/struct.Query.html#method.explain_plan

**Comment by laonger** [comment]
Ok, here is Python's explain: 
```
In [104]: print(t.search(v).explain_plan())
ProjectionExec: expr=[file@3 as file, md5@4 as md5, code_type@5 as code_type, lang@6 as lang, name@7 as name, purpose@8 as purpose, content@9 as content, embedings@0 as embedings, _distance@2 as _distance]
  Take: columns="embedings, _rowid, _distance, file, md5, code_type, lang, name, purpose, content"
    FilterExec: _distance@2 IS NOT NULL
      SortExec: TopK(fetch=10), expr=[_distance@2 ASC NULLS LAST], preserve_partitioning=[false]
        KNNVectorDistance: metric=l2
          LanceScan: uri=Users/laonger/Documents/Work/self/readit/.readit/db/vectors.lance/data, projection=[embedings], row_id=true, row_addr=false, ordered=false
```

and here is Rust's: 
```
explain: 
ProjectionExec: expr=[file@3 as file, md5@4 as md5, code_type@5 as code_type, lang@6 as lang, name@7 as name, purpose@8 as purpose, content@9 as content, embedings@0 as embedings, _distance@2 as _distance]
  Take: columns="embedings, _rowid, _distance, file, md5, code_type, lang, name, purpose, content"
    CoalesceBatchesExec: target_batch_size=8192
      GlobalLimitExec: skip=0, fetch=10
        FilterExec: _distance@2 IS NOT NULL
          SortExec: TopK(fetch=10), expr=[_distance@2 ASC NULLS LAST], preserve_partitioning=[false]
            KNNVectorDistance: metric=l2
              LanceScan: uri=Users/laonger/Documents/Work/self/readit/.readit/db/vectors.lance/data, projection=[embedings], row_id=true, row_addr=false, ordered=false
```


> I still think it's likely there are just different defaults between Rust and Python. I'd recommend calling `explain_plan()` on each and posting them here. Then we can find what differences there are in what they are executing.
> 
> https://lancedb.github.io/lancedb/python/python/#lancedb.query.LanceQueryBuilder.explain_plan https://docs.rs/lancedb/latest/lancedb/query/struct.Query.html#method.explain_plan
