### ISSUE TITLE
bug(python): JoinError::Panic(Id(1002), \"the offset of the new Buffer cannot exceed the existing length:

### ISSUE THREAD

**Issue by mjmdavis** [lancedb/lancedb#2154]
### LanceDB version

0.19.0

### What happened?

Performed a query on a column and the error occurred.

query:
```
tbl.search(target).to_list()
```

```
target.shape
(768,)

target.dtype
dtype('float32')

type(target)
numpy.ndarray
```
```
tbl.schema:

name: large_string
scryfallId: large_string
manaCost: large_string
type: large_string
text: large_string
power: large_string
toughness: large_string
loyalty: large_string
rarities: large_list<item: dictionary<values=large_string, indices=uint32, ordered=0>>
  child 0, item: dictionary<values=large_string, indices=uint32, ordered=0>
    -- field metadata --
    _PL_ENUM_VALUES: '6;common8;uncommon4;rare6;mythic5;bonus7;special'
sets: large_list<item: dictionary<values=large_string, indices=uint32, ordered=0>>
  child 0, item: dictionary<values=large_string, indices=uint32, ordered=0>
    -- field metadata --
    _PL_ENUM_VALUES: '3;LEA3;LEB3;2ED3;CED3;CEI3;ARN3;ATQ3;3ED3;FBB3;LEG3' + 4289
embedding: fixed_size_list<item: float>[768]
  child 0, item: float
x_2d: float
y_2d: float
```
